spring.application.name=TicketSupport

# Database Configuration
spring.datasource.url=jdbc:postgresql://localhost:5432/ticket_support_db
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}

# JPA Configuration
spring.jpa.hibernate.ddl-auto=none

# Liquibase Configuration
spring.liquibase.enabled=true
spring.liquibase.change-log=classpath:db/changelog/changelog-master.xml

# Message Configuration
spring.messages.basename=messages